// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2LdUEQwe5Yxmk87OS6ERMjeqUkUmd3Ag',
    appId: '1:1087818568064:web:15ac87d62fe2bb641db165',
    messagingSenderId: '1087818568064',
    projectId: 'nutriglow-3513c',
    authDomain: 'nutriglow-3513c.firebaseapp.com',
    storageBucket: 'nutriglow-3513c.appspot.com',
    measurementId: 'G-YDDFYY00DE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBj9VFIIB126KeKbbtFs456ka-78e3Q7U',
    appId: '1:1087818568064:android:bedfd57f0558b1301db165',
    messagingSenderId: '1087818568064',
    projectId: 'nutriglow-3513c',
    storageBucket: 'nutriglow-3513c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0WhMe4oc00n-mxTLkgmOF0AKPXLme1TM',
    appId: '1:1087818568064:ios:765886f31e35792b1db165',
    messagingSenderId: '1087818568064',
    projectId: 'nutriglow-3513c',
    storageBucket: 'nutriglow-3513c.appspot.com',
    iosClientId: '1087818568064-71lvf1vl3hikeosfcbiuu3p2tor20oe0.apps.googleusercontent.com',
    iosBundleId: 'com.example.nutriGlow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0WhMe4oc00n-mxTLkgmOF0AKPXLme1TM',
    appId: '1:1087818568064:ios:765886f31e35792b1db165',
    messagingSenderId: '1087818568064',
    projectId: 'nutriglow-3513c',
    storageBucket: 'nutriglow-3513c.appspot.com',
    iosClientId: '1087818568064-71lvf1vl3hikeosfcbiuu3p2tor20oe0.apps.googleusercontent.com',
    iosBundleId: 'com.example.nutriGlow',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB2LdUEQwe5Yxmk87OS6ERMjeqUkUmd3Ag',
    appId: '1:1087818568064:web:673f4f8338c3010e1db165',
    messagingSenderId: '1087818568064',
    projectId: 'nutriglow-3513c',
    authDomain: 'nutriglow-3513c.firebaseapp.com',
    storageBucket: 'nutriglow-3513c.appspot.com',
    measurementId: 'G-7YGNL206G3',
  );
}
